< $PLAN9/src/mkhdr

BINDIR= $HOME/bin
TARG=padsterm

OFILES= buttons.o cache.o cursor.o host.o io.o lib.o \
	lineops.o master.o pad.o paint.o plan9.o protocol.o \
	scripthit.o time.o

# -DHALFDUP -DTAGS -DSCROLL -DSAMTERM -DBLANCHEDALMOND
DEFS= -DHALFDUP -DSCROLL -DSAMTERM -DTAGS
INCLUDE = -I..
CFLAGS= -g $INCLUDE $DEFS
LDFLAGS= -g
LDLIBS=

CLEANFILES=$CLEANFILES $PROG *.core files.cs cscope.out

PROG=$TARG

all:V:  $BINDIR/$PROG

$PROG:  $OFILES $LIB # ${SHORTLIB:%=$LIBDIR/lib%.a}
	$LD $LDFLAGS -o $target $prereq $LDLIBS

install:V: $BINDIR/$PROG

$BINDIR/$PROG: $PROG
	rm -f $BINDIR/$PROG
	$INSTALL $PROG $BINDIR/$PROG

CLEANFILES=$CLEANFILES $PROG
NUKEFILES=$NUKEFILES $BIN/$TARG

<$PLAN9/src/mkcommon

alloc.o:     alloc.c     univ.h ../pads.h
buttons.o:   buttons.c   univ.h ../pads.h
cache.o:     cache.c     univ.h ../pads.h
cursor.o:    cursor.c    univ.h ../pads.h
host.o:      host.c      univ.h ../pads.h
lib.o:       lib.c       univ.h ../pads.h
lineops.o:   lineops.c   univ.h ../pads.h
master.o:    master.c    univ.h ../pads.h
pad.o:       pad.c       univ.h ../pads.h
paint.o:     paint.c     univ.h ../pads.h
protocol.o:  protocol.c  univ.h ../pads.h
scripthit.o: scripthit.c univ.h ../pads.h
