< ../ADM/defns
< ../index/defns

PIC=/plan9/bin/pic
TROFF=/plan9/bin/troff
FEELSO=binps.so jim.so RUN1.so srctext.so srcfiles.so index.so compile.so\
	setbpt.so gtgtgt.so bpt.so callstack.so jimc.so run.so step1stmt.so\
	fexec.so openframe.so startchar.so asciion.so a97.so assign.so typeof.so\
	left.so op.so star.so right.so rr.so thelast.so 

all:V:	feel.out

pg:	feel.out
	count feel.ms feel.out

spell:VQ:
	dospell feel.ms

lp:	feel.out
	$LP $newprereq && touch $target

feel.out:D:	feel.ms $REF $FEELSO
	cat ../ADM/bm.mac feel.ms | $PREFER | $TROFF -mpm | ../ADM/bm.sh > $target

index:V: feel
feel:V:
	sh ../index/runind feel
	cat ../ADM/bm.mac xfeel.ms | $PREFER | $TROFF -mpm  > /dev/null 2>feel.x
	sh ../index/mkindex feel.x
	rm xfeel.ms

pindex:V:
	mkindex feel.x
