#! /bin/sh

#uses either $1.x or $2.x to make base.ind
	if test $# -eq 0
	then
		echo mkindex directory file or mkindex file
		exit
	fi
	if test $# -eq 1
	then
	j=`basename $1 .x`
	sed -n "/^\\.XX.*$j/p" ../contents/contents.ms|awk '{print $2 >"name"}'
	else
	j=`basename $2 .x`
	sed -n "/^\\.XX.*$1\\/$j/p" ../contents/contents.ms|awk '{print $2 >"name"}'
	fi
	FILE=$j.x
	if test -f $j.sed2
	then
		sed -f $j.sed2 $FILE >x$FILE
		FILE=x$FILE
	fi
S=`cat name`
sed -e "/^[01]	/d" -e "s/ #.*//" -e "s/:/;/g" -e "/^[A-Za-z.]/d" -e "/Examp/d" $FILE|
awk '
BEGIN	{FS="	" }
NF==2	{ print str ", " $2 ": " $1
	print $2 ", " str ": " $1
	}
NF==3	{
	if($NF ~ /s/ )print str ", " $2 ": " $1
	else if($NF ~ /[SprtqxyzZY]/ )print str ", " $2 ": " $1 ":" $NF
	else if($NF ~ /[gGPR]/) print $2 ", " str ": " $1 ":" $NF
	else if($NF ~ /[cf]/){
		print str ", " $2 ": " $1 ":" $NF
		print $2 ", " str ": " $1 ":" $NF
	}
	else if($NF ~ /C/){
		print str ", " $2 ": " $1 ":" $NF
		print $2 ", " str ": " $1 
	}
	else print "code undefined:" $NF|"cat 1>&2"
}' str=$S | sort -f -u -t":" +0 -1 +1n |
awk '
BEGIN	{FS=":"}
	{ if($1 != laststr){
		if(start){
			if(range)pages = pages "-" npage
			if(global != "")print laststr "," pages "	" global
			else print laststr "," pages
		}
		start=1
		laststr=$1
		global=$3
		pages = " " $2
		npage = 0 + $2
		range=0
	}
	else {
		if($2 == npage+1){
			range=1
			npage++
			next
		}
		else if(range) pages = pages "-" npage "," $2
		else pages = pages "," $2
		npage = 0 + $2
		range = 0
	}
}
END	{
	if(range)pages = pages "-" npage
	if(global != "")print laststr "," pages "	" global
	else print laststr "," pages
	}' | sed -e 's/~/\$/g' -e 's/;/:/g' > $j.ind
rm name $j.x
